### ISSUE TITLE
An old version of 'getbypath' on the npmjs.com

### ISSUE THREAD

**Issue by drfisher** [chovy/getbypath#4]
There is an old version of 'getbypath' on the npmjs.com - https://www.npmjs.com/package/getbypath
It doesn't contain the last fix from the pull request https://github.com/chovy/getbypath/pull/3

**Comment by ralyodio** [comment]
Can you add some unit tests? I was waiting to write those.

**Comment by drfisher** [comment]
@chovy, sure. I'll do it on this week.

**Comment by ralyodio** [comment]
new version 1.1.0 has been released
